#!/bin/sh

echo Compiling
clang -target le1 -O0 -emit-llvm -c $1 -o test.bc
llvm-link test.bc /opt/esdg-opencl/lib/builtins.bc -o linked-float.bc
llc linked-float.bc -o float.s

echo Transforming assembly file
perl ~/llvmTransform.pl float.s > final.s
echo Running second pass
perl ~/Dropbox/src/LE1/Assembler/secondpass.pl final.s -OPC=/opt/esdg-opencl/include/opcodes.txt
echo Starting Insizzle
~/Dropbox/src/LE1/Insizzle/INSIZZLE /opt/esdg-opencl/machines/Default_1wide.xml -printout
