/*
  striped down version of vtapi.h to just contain the galaxyConfigT
 */

#ifndef _GUARD_GALAXYCONFIG_
#define _GUARD_GALAXYCONFIG_

#define MASTERCFG_SYSTEMS_MAX       0x1
#define MASTERCFG_CONTEXTS_MAX      0x1
#define MASTERCFG_CLUST_TEMPL_MAX   0x1
#define MASTERCFG_HYPERCONTEXTS_MAX 0x1

#define S_GPR_FILE_SIZE_MAX         64
#define S_PRED_FILE_SIZE_MAX        0x8

#define VT32PP                      0x0
#define VT64PP                      0x1
#define VT32EPIC                    0x2
#define VT64EPIC                    0x3

/*typedef enum {
  DEBUG=0,
  SSTEP_READY=1,
  SSTEP_RUNNING=2,
  SSTEP_BLOCKED_MUTEX_LOCK=3,
  SSTEP_TERMINATED_SYNC=4,
  READY=5,
  RUNNING=6,
  BLOCKED_MUTEX_LOCK=7,
  TERMINATED_ASYNC_HOST=8,
  TERMINATED_ASYNC=9,
  TERMINATED_SYNC=10
} vtCtrlStateE;*/


typedef struct {
  /*vtCtrlStateE VT_CTRL[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_HYPERCONTEXTS_MAX];*/ /* VT_CTRL_REG */
  int VT_CTRL[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_HYPERCONTEXTS_MAX]; /* VT_CTRL_REG */
  int GALAXY_CONFIG;
  int SYSTEM_CONFIG[MASTERCFG_SYSTEMS_MAX];
  int PERIPH_WRAP_CONFIG[MASTERCFG_SYSTEMS_MAX];
  int DRAM_SHARED_CONFIG0[MASTERCFG_SYSTEMS_MAX];
  int DRAM_SHARED_CTRL[MASTERCFG_SYSTEMS_MAX];
  int VTHREADS_CONFIG[MASTERCFG_SYSTEMS_MAX];
  int CONTEXT_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX];
  int CONTEXT_CTRL[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX];
  int IFE_SIMPLE_IRAM_PRIV_CONFIG0[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX];
  int CLUST_TEMPL_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int HCONTEXT_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_HYPERCONTEXTS_MAX];
  int CLUST_TEMPL_STATIC_REGFILE_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_SCORE_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CCORE7_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CCORE6_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CCORE5_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CCORE4_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CCORE3_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CCORE2_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];

  int CLUST_TEMPL_CASM6X1_XISA0_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CASM6X1_XISA1_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CASM5X2_XISA0_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CASM5X2_XISA1_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CASM4X3_XISA0_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CASM4X3_XISA1_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CASM3X4_XISA0_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CASM3X4_XISA1_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];

  int CLUST_TEMPL_CASM5X1_XISA0_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CASM5X1_XISA1_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CASM4X2_XISA0_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CASM4X2_XISA1_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CASM3X3_XISA0_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CASM3X3_XISA1_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CASM2X4_XISA0_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CASM2X4_XISA1_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];

  int CLUST_TEMPL_CASM4X1_XISA0_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CASM4X1_XISA1_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CASM3X2_XISA0_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CASM3X2_XISA1_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CASM2X3_XISA0_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CASM2X3_XISA1_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];

  int CLUST_TEMPL_CASM3X1_XISA0_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CASM3X1_XISA1_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CASM2X2_XISA0_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CASM2X2_XISA1_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CASM1X3_XISA0_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CASM1X3_XISA1_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];

  int CLUST_TEMPL_CASM2X1_XISA0_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CASM2X1_XISA1_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CASM1X2_XISA0_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CASM1X2_XISA1_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];

  int CLUST_TEMPL_CASM1X1_XISA0_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];
  int CLUST_TEMPL_CASM1X1_XISA1_CONFIG[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_CLUST_TEMPL_MAX];

  int HCONTEXT_CLUST_TEMPL0[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_HYPERCONTEXTS_MAX];
  int HCONTEXT_CLUST_TEMPL1[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_HYPERCONTEXTS_MAX];

  int HCONTEXT_CLUST_TEMPL_INST0[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_HYPERCONTEXTS_MAX];
  int HCONTEXT_CLUST_TEMPL_INST1[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_HYPERCONTEXTS_MAX];
} ctrlStateT;


typedef struct {
  int sGpr[MASTERCFG_CLUST_TEMPL_MAX][S_GPR_FILE_SIZE_MAX];
  int sPr [MASTERCFG_CLUST_TEMPL_MAX][S_PRED_FILE_SIZE_MAX];
  int lr;
  int pc;
} oneArchStateT;


typedef struct {
  oneArchStateT oneArchState[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX][MASTERCFG_HYPERCONTEXTS_MAX];
  int * iRam[MASTERCFG_SYSTEMS_MAX][MASTERCFG_CONTEXTS_MAX];
  int * dRam[MASTERCFG_SYSTEMS_MAX];
} fullArchStateT;


typedef struct {
  int system_reg;
  int context_reg;
  int hypercontext_reg;
  int cluster_reg;
  int addr_reg;
  int busy_reg;
  int wrdata1_reg;
  int wrdata2_reg;
  int rddata1_reg;
  int rddata2_reg;
  int response_reg;
  int streaming_ctrl_reg;
} debugStateT;


struct {
  ctrlStateT 	ctrlState;
  debugStateT 	debugState;
  fullArchStateT galaxyConfigT;
} galaxyConfigT;

struct galaxyConfigT galaxyConfig;

#endif
