/* definitions of syscalls */
#define PRINTF     0
#define FOPEN      1
#define FCLOSE     2
#define FWRITE     3
#define FREAD      4
#define FPRINTF    5
#define FSEEK      6
#define FTELL      7
#define SNPRINTF   8
#define CLOCK      9
#define FSCANF    10
#define FGETC     11
#define UNGETC    12
#define ATOI      13
#define SRAND     14
#define RAND      15
#define SPRINTF   16
#define SSCANF    17
#define FPUTC     18
#define OPEN      19
#define CLOSE     20
#define READ      21
#define WRITE     22
#define LSEEK     23
#define FSTAT     24
#define STRTOL    25
#define STRTOD    26
